from setuptools import setup

with open("README.md", 'r') as f:
    long_description = f.read()

setup(
    name='artifact_manager',
    version='0.1',
    description='A python library to manage artifacts generated by data science projects.',
    author='Anderson Gonçalves Maroc',
    url='https://github.com/AndersonMarco/artifact_manager',
    install_requires=['rclone_python'],
    packages=['artifactmanager'],
    long_description=long_description,
    long_description_content_type="text/markdown",
    keywords=['data science', 'mlops','rclone', 'library', 'cloud sync'],
    python_requires='>=3.6',
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ]
)
